name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  PHP_CodeSniffer:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: php-cs
        uses: docker://oskarstark/phpcs-ga:3.4.2
        with:
          args: src/ --standard=psr12 --exclude=Generic.Files.LineEndings
  PHPUnit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: php-actions/composer@v5
#        with:
#          php_version: 7.0
      - name: phpunit
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml
          version: 6.5
          php_version: 7.0
