name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  PHP_CodeSniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: php-cs
        uses: docker://oskarstark/phpcs-ga:3.4.2
        with:
          args: src/ --standard=psr12 --exclude=Generic.Files.LineEndings
