name: CI

on:
  push:
    branches:
      - master
      - hotfix/**
      - develop
      - feature/**
      - release/**
  pull_request:
    branches:
      - master
      - hotfix/**
      - develop
      - feature/**
      - release/**
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.0

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run code sniffer
        run: composer run-script code-sniffer

      - name: Run test suite
        run: composer run-script tests
